(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var c="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},d;if("function"==typeof Object.setPrototypeOf)d=Object.setPrototypeOf;else{var e;a:{var f={a:!0},g={};try{g.__proto__=f;e=g.a;break a}catch(a){}e=!1}d=e?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var h=d,k=this||self;function l(a,b){this.g=a===n&&b||"";this.j=p}l.prototype.i=!0;l.prototype.h=function(){return this.g};var p={},n={};var q=new l(n,"_newtab");function r(a,b){this.g=b===t?a:""}r.prototype.i=!0;r.prototype.h=function(){return this.g.toString()};r.prototype.toString=function(){return this.g.toString()};var u=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,t={};function v(){var a=HTMLElement.call(this)||this;a.i=!1;a.l=a.m.bind(a);a.h=null;a.j=null;return a}var w=HTMLElement;v.prototype=c(w.prototype);v.prototype.constructor=v;if(h)h(v,w);else for(var x in w)if("prototype"!=x)if(Object.defineProperties){var y=Object.getOwnPropertyDescriptor(w,x);y&&Object.defineProperty(v,x,y)}else v[x]=w[x];
v.prototype.connectedCallback=function(){var a=this;this.i||(document.body.style.opacity="0");setTimeout(function(){a.g=a.querySelector("gwd-pagedeck");a.h=document.querySelector("gwd-responsive-attributes-helper");a.h&&a.h.applyOverrides();window.addEventListener("resize",a.l,!1)},0)};v.prototype.disconnectedCallback=function(){window.removeEventListener("resize",this.l,!1)};
v.prototype.initAd=function(){this.i=!0;document.body.style.opacity="";var a=void 0===a?null:a;var b=document.createEvent("CustomEvent");b.initCustomEvent("adinitialized",!0,!0,a);this.dispatchEvent(b);this.goToPage()};v.prototype.goToPage=function(a,b,m,z,A){if(a=void 0!=a?this.g.getPage(a):this.g.getDefaultPage())a=this.g.getOrientationSpecificPage(window.innerHeight>=window.innerWidth?1:2,a.id),void 0!=b?this.g.goToPage(a.id,b,m,z,A):this.g.goToPage(a.id)};
v.prototype.m=function(){this.i&&this.h&&this.h.applyOverrides();var a=window.innerHeight>=window.innerWidth?1:2;this.j!=a&&(this.j=a,(a=this.g.getPage(Number(this.g.currentIndex)))&&this.goToPage(a.id))};
v.prototype.exit=function(a,b,m){b=void 0===b?!1:b;a instanceof r||a instanceof r||(a="object"==typeof a&&a.i?a.h():String(a),u.test(a)||(a="about:invalid#zClosurez"),a=new r(a,t));k.open(a instanceof r&&a.constructor===r?a.g:"type_error:SafeUrl",q instanceof l?q instanceof l&&q.constructor===l&&q.j===p?q.g:"type_error:Const":q||"");b&&this.goToPage(m)};customElements.define("gwd-genericad",v);}).call(this);
